# Generated by Django 4.1.1 on 2022-09-27 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_persona',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=15, unique=True, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido')),
                ('edad', models.SmallIntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tbl_rol',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_familiar',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_paciente',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(max_length=30)),
                ('id_medico', models.SmallIntegerField()),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_familiar')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_persona',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_rol'),
        ),
        migrations.AddField(
            model_name='tbl_persona',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='tbl_signovital',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('oximetria', models.SmallIntegerField()),
                ('frec_respiratoria', models.SmallIntegerField()),
                ('frec_cardiaca', models.SmallIntegerField()),
                ('temperatura', models.SmallIntegerField()),
                ('presion_arterial', models.SmallIntegerField()),
                ('glicemias', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_paciente')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_historia',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_paciente')),
            ],
        ),
    ]
