# Generated by Django 4.1.1 on 2022-09-30 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='personaModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=15, verbose_name='Apellido')),
                ('edad', models.SmallIntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rolModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='familiarModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pacienteModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion', models.CharField(max_length=50)),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.familiarmodel')),
            ],
        ),
        migrations.AddField(
            model_name='personamodel',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.rolmodel'),
        ),
        migrations.AddField(
            model_name='personamodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='signosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.IntegerField()),
                ('f_respiratoria', models.IntegerField()),
                ('f_cardiaca', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('presion_arterial', models.IntegerField()),
                ('glicemias', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.pacientemodel')),
            ],
        ),
        migrations.CreateModel(
            name='historialModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.pacientemodel')),
            ],
        ),
    ]
