# Generated by Django 4.1.1 on 2022-09-21 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_persona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_familiar',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='appHospital.tbl_persona')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_paciente',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='appHospital.tbl_persona')),
                ('direccion', models.CharField(max_length=30)),
                ('id_medico', models.IntegerField()),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_familiar')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_persona',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_rol'),
        ),
        migrations.CreateModel(
            name='tbl_signovital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('oximetria', models.IntegerField()),
                ('frec_respiratoria', models.IntegerField()),
                ('frec_cardiaca', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('presion_arterial', models.IntegerField()),
                ('glicemias', models.IntegerField()),
                ('fecha', models.DateField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_paciente')),
            ],
        ),
        migrations.AlterField(
            model_name='tlb_historia',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.tbl_paciente'),
        ),
    ]
