# Generated by Django 4.1.1 on 2022-09-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0002_tbl_persona_tbl_rol_tbl_familiar_tbl_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_paciente',
            name='id_medico',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_persona',
            name='edad',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_persona',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_rol',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='frec_cardiaca',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='frec_respiratoria',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='glicemias',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='oximetria',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='presion_arterial',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_signovital',
            name='temperatura',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tlb_historia',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
