# Generated by Django 4.1.1 on 2022-09-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0003_alter_personamodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personamodel',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
