# Generated by Django 4.1.1 on 2022-09-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0004_alter_personamodel_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_rol',
            new_name='rolModel',
        ),
    ]
