# Generated by Django 4.1.1 on 2022-09-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0005_rename_tbl_rol_rolmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personamodel',
            name='id_rol',
            field=models.SmallIntegerField(choices=[(1, 'Medico'), (2, 'Padre')], max_length=1),
        ),
    ]
