# Generated by Django 4.1.1 on 2022-09-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0006_alter_personamodel_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personamodel',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appHospital.rolmodel'),
        ),
    ]
