# Generated by Django 4.1.1 on 2022-09-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0007_alter_personamodel_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personamodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
