# Generated by Django 4.1.1 on 2022-09-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0008_alter_personamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
